version: '3'
services:
  webapp:
    image: test_fastapi_webapp:1.1
    networks:
      - custom

  reverse_proxy:
    image: nginx:1.25.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html
    depends_on:
      - webapp
    networks:
      - custom

networks:
  custom:
    driver: bridge
